### PR TITLE
Enable pytest in CI

### PR DESCRIPTION
**Pull request by EwoutH**
This PR enables pytest in both GitHub Actions and Travis CI.

At this moment pytest fails [because it can't locate a two data files](https://github.com/EwoutH/biogeme/runs/784426200?check_suite_focus=true#step:8:29). They're included in the repository, but maybe in the wrong directory. I don't know yet if it's an error on pytest's side or the problem is with the test itself. @michelbierlaire, where do you normally store the data (.dat) files when running the tests?

Errors (23 total):
```
FileNotFoundError: [Errno 2] File swissmetro.dat does not exist: 'swissmetro.dat'
FileNotFoundError: [Errno 2] File optima.dat does not exist: 'optima.dat'
```
This is a Draft PR, so please wait with merging until it's marked as ready (in green).

### CODE REVIEW

**Comment by michelbierlaire** [comment]
What does pytest execute exactly? The "simple_test.py" script runs without the need of a data file.

**Comment by EwoutH** [comment]
At the moment it [tries](https://github.com/michelbierlaire/biogeme/runs/784482400#step:8:9) to run all the tests in the tests directory.

**Comment by EwoutH** [comment]
Tried adding the other tests, but I kept getting either the tests not being found or the files that were needed didn't get found.

Now it just runs the `simple_test.py`.

**Comment by michelbierlaire** [comment]
The data sets are in the same directories as the tests themselves. For instance, 
https://github.com/michelbierlaire/biogeme/blob/working/tests/swissmetro/swissmetro.dat
Note that some of these tests take a while. Therefore, they are not appropriate for automatic testing. I usually run them on a server before publishing a release. What I can do is to prepare a series of tests that would be suitable for automatic testing, still more sophisticated than the simple_test.py.

**Pull request merged**
