### PR TITLE
Switch to Pipfiles and add CI

### PR DESCRIPTION
**Pull request by EwoutH**
This PR switches from a requirements.txt to a Pipfile and adds some very basic continuous integration.

The `requirements.txt` is deleted and replaced by a `Pipfile`. In the Pipfile requirements can be added and versions can be specified. The exact versions then get locked in the `Pipfile.lock` so that builds are deterministic and reproducible. I also added workflow (`update-pipfile.yml`) that opens a PR once a week to update the Pipfile.lock. The frequency and timing can be adjusted ([cron](https://crontab.guru/) is used).

See [Pipenv: Python Dev Workflow for Humans](https://pipenv-fork.readthedocs.io/en/latest/) for more information about the Pipfile and the use of Pipenv.

Secondly some very basic CI is added. Both Travis and GitHub Actions run `python setup.py install` after cloning and installing the dependencies. I also tried pytest, but at this moment it gave too many errors to be solved in this PR. After this PR is merged, I will dive further into this.

@michelbierlaire I'm curious what you think. If you have any questions of suggestions let me know!

### CODE REVIEW

**Comment by michelbierlaire** [comment]
Thanks for that. But, please wait. The Github repository is not finalized yet. My plan is to finalize the next version of the software, upload it to pypy, and tag it on github. Then, I will have a "release" and a "development" branch.
Also, what happens for the Windows binaries? What consequences will it have?

**Comment by EwoutH** [comment]
Thanks for the quick reply. I will leave this PR open for a bit. Maybe put some of this info in the Readme.

The Windows binaries will be generated as usual, only now the dependencies will be read from the Pipfile.lock instead of the Requirements file.

**Comment by michelbierlaire** [comment]
The new version is almost ready. I need to find the time to update the documentation and the webpage. Hopefully sometimes in June.

**Comment by EwoutH** [comment]
Great to here! Consider updating the development branch a bit earlier. That way users can do code reviews and testing and give feedback before the official release.

**Comment by EwoutH** [comment]
@michelbierlaire Congratulations on releasing 3.2.6! Could you let me know when you're interested in switching to Pipenv? When that's the case I will rebase this PR and update the Pipfiles.

**Comment by michelbierlaire** [comment]
Thank you, Ewout. Yes, I am interested. Can we have a discussion first via Zoom? Pls send me a direct email.

**Comment by EwoutH** [comment]
@michelbierlaire Sure, no problem, I will email you. I can recommend reading [Pipenv: A Guide to the New Python Packaging Tool](https://realpython.com/pipenv-guide/) first, to get an understanding what problems that Pipenv solves and how it works.

**Pull request merged**
